const MOCK_PRODUCTS = [
    // 牛仔裤
    {
        id: 'tb_jeans_001',
        title: '高腰微喇牛仔裤女春秋新款显瘦百搭黑色弹力修身马蹄裤',
        price: 128,
        originalPrice: 256,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '微喇',
        season: '春秋',
        material: '棉弹牛仔布',
        size: ['S', 'M', 'L', 'XL'],
        sales: 12000,
        rating: 4.7,
        tags: ['高腰', '显瘦', '百搭', '弹力'],
        reason: '高腰设计拉长腿部线条，微喇版型修饰腿型，黑色经典百搭，适合春秋季节穿搭。'
    },
    {
        id: 'jd_jeans_002',
        title: 'ONLY 高腰阔腿牛仔裤女显瘦垂感直筒裤春秋新款黑色',
        price: 199,
        originalPrice: 399,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '阔腿',
        season: '春秋',
        material: '棉混纺',
        size: ['26', '27', '28', '29', '30'],
        sales: 8500,
        rating: 4.8,
        tags: ['高腰', '显瘦', '垂感', '直筒'],
        reason: 'ONLY品牌品质保证，阔腿设计遮肉显瘦，垂感面料穿着舒适，经典黑色永不过时。'
    },
    {
        id: 'pdd_jeans_003',
        title: '微喇牛仔裤女高腰显瘦2024春秋新款黑色弹力小喇叭裤',
        price: 89,
        originalPrice: 179,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '微喇',
        season: '春秋',
        material: '弹力牛仔',
        size: ['S', 'M', 'L'],
        sales: 35000,
        rating: 4.5,
        tags: ['高腰', '微喇', '显瘦', '弹力'],
        reason: '超高性价比，弹力面料舒适不紧绷，微喇版型复古时尚，好评率超高。'
    },
    {
        id: 'tb_jeans_004',
        title: '黑色直筒牛仔裤女高腰春秋新款宽松显瘦百搭九分裤',
        price: 159,
        originalPrice: 318,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '直筒',
        season: '春秋',
        material: '纯棉牛仔',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 6800,
        rating: 4.6,
        tags: ['高腰', '直筒', '宽松', '九分'],
        reason: '直筒版型不挑身材，九分长度显腿长，纯棉面料透气舒适。'
    },
    {
        id: 'jd_jeans_005',
        title: 'Lee高腰微喇牛仔裤女黑色弹力修身显瘦春秋款长裤',
        price: 459,
        originalPrice: 899,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1506629082955-511b1aa2c6a9?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '微喇',
        season: '春秋',
        material: '优质牛仔布',
        size: ['25', '26', '27', '28', '29', '30'],
        sales: 3200,
        rating: 4.9,
        tags: ['Lee', '高腰', '微喇', '品牌'],
        reason: 'Lee经典品牌，优质牛仔面料，版型做工精湛，虽价格较高但品质卓越。'
    },
    {
        id: 'tb_jeans_006',
        title: '复古微喇牛仔裤女高腰春秋黑色显瘦拖地马蹄裤ins风',
        price: 168,
        originalPrice: 336,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1475178626620-a4d074967c1b?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '微喇',
        season: '春秋',
        material: '棉弹面料',
        size: ['S', 'M', 'L'],
        sales: 9500,
        rating: 4.6,
        tags: ['复古', '高腰', '拖地', 'ins风'],
        reason: '复古微喇拖地设计显腿长，ins风潮流款式，搭配高跟鞋气场全开。'
    },
    // 运动鞋
    {
        id: 'tb_shoes_001',
        title: '夏季透气网面运动鞋女轻便软底跑步鞋白色休闲百搭小白鞋',
        price: 168,
        originalPrice: 336,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '休闲',
        season: '夏季',
        material: '网面',
        size: ['35', '36', '37', '38', '39', '40'],
        sales: 28000,
        rating: 4.7,
        tags: ['透气', '轻便', '跑步', '小白鞋'],
        reason: '网面透气设计，夏季不闷脚，轻便软底适合跑步和日常穿搭，白色百搭。'
    },
    {
        id: 'jd_shoes_002',
        title: '安踏氢跑鞋夏季透气网面运动鞋男轻便跑步鞋白色',
        price: 269,
        originalPrice: 399,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '跑步',
        season: '夏季',
        material: '氢科技网面',
        size: ['39', '40', '41', '42', '43', '44'],
        sales: 45000,
        rating: 4.8,
        tags: ['安踏', '氢科技', '透气', '跑步'],
        reason: '安踏氢科技超轻鞋身，专业跑步设计，网面透气，品牌品质有保障。'
    },
    {
        id: 'pdd_shoes_003',
        title: '回力小白鞋女夏季透气帆布鞋百搭休闲运动鞋白色',
        price: 59,
        originalPrice: 129,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '休闲',
        season: '夏季',
        material: '帆布',
        size: ['35', '36', '37', '38', '39'],
        sales: 62000,
        rating: 4.4,
        tags: ['回力', '帆布', '小白鞋', '百搭'],
        reason: '国货经典回力品牌，超高性价比，帆布鞋透气舒适，学生党首选。'
    },
    {
        id: 'tb_shoes_004',
        title: '特步减震跑步鞋男夏季透气网面运动鞋白色轻便跑鞋',
        price: 189,
        originalPrice: 359,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '跑步',
        season: '夏季',
        material: '网面',
        size: ['39', '40', '41', '42', '43'],
        sales: 18000,
        rating: 4.6,
        tags: ['特步', '减震', '透气', '跑步'],
        reason: '特步专业减震科技，保护膝盖，透气网面适合夏季长跑训练。'
    },
    // 面霜
    {
        id: 'tb_face_001',
        title: '珂润润浸保湿滋养面霜40g 敏感肌适用补水滋润修护',
        price: 188,
        originalPrice: 280,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['40g'],
        sales: 56000,
        rating: 4.9,
        tags: ['珂润', '敏感肌', '保湿', '修护'],
        reason: '珂润专为敏感肌设计，神经酰胺修护屏障，温和无刺激，口碑爆款。'
    },
    {
        id: 'jd_face_002',
        title: '理肤泉B5修复面霜40ml 敏感肌修护舒缓泛红保湿',
        price: 129,
        originalPrice: 199,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['40ml'],
        sales: 42000,
        rating: 4.8,
        tags: ['理肤泉', 'B5', '修护', '敏感肌'],
        reason: '理肤泉B5经典修复霜，泛醇修护受损肌肤，舒缓泛红，药妆品牌安全放心。'
    },
    {
        id: 'pdd_face_003',
        title: '薇诺娜舒敏保湿特护霜50g 敏感肌修护屏障补水面霜',
        price: 168,
        originalPrice: 268,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['50g'],
        sales: 38000,
        rating: 4.7,
        tags: ['薇诺娜', '舒敏', '特护', '敏感肌'],
        reason: '国产药妆之光，青刺果油修护屏障，专为敏感肌研发，医院推荐品牌。'
    },
    {
        id: 'tb_face_004',
        title: 'FAB急救美人面霜170g 强效修护保湿敏感肌可用',
        price: 89,
        originalPrice: 199,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['170g'],
        sales: 25000,
        rating: 4.6,
        tags: ['FAB', '急救', '修护', '大容量'],
        reason: '平价版La Mer，大容量超实惠，急救修护效果显著，适合干敏肌。'
    },
    {
        id: 'jd_face_005',
        title: '丝塔芙大白罐保湿面霜550g 敏感肌身体乳面霜两用',
        price: 128,
        originalPrice: 198,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['550g'],
        sales: 72000,
        rating: 4.9,
        tags: ['丝塔芙', '大白罐', '身体乳', '大容量'],
        reason: '550g超大容量，面部身体两用，温和配方全家可用，性价比之王。'
    },
    // 衬衫
    {
        id: 'tb_shirt_001',
        title: '商务休闲衬衫男长袖浅蓝色修身款免烫抗皱上班正装',
        price: 138,
        originalPrice: 276,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '浅蓝色',
        style: '商务休闲',
        season: '四季',
        material: '棉混纺',
        size: ['38', '39', '40', '41', '42', '43'],
        sales: 15000,
        rating: 4.6,
        tags: ['商务', '免烫', '修身', '上班'],
        reason: '免烫抗皱面料省心好打理，修身版型精神干练，浅蓝色商务百搭。'
    },
    {
        id: 'jd_shirt_002',
        title: '雅戈尔长袖衬衫男浅蓝色商务正装纯棉免烫上班衬衣',
        price: 259,
        originalPrice: 499,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '浅蓝色',
        style: '商务正装',
        season: '四季',
        material: '纯棉',
        size: ['39', '40', '41', '42'],
        sales: 8900,
        rating: 4.8,
        tags: ['雅戈尔', '纯棉', '免烫', '正装'],
        reason: '雅戈尔国民衬衫品牌，纯棉免烫DP工艺，商务正装首选，品质有保障。'
    },
    {
        id: 'pdd_shirt_003',
        title: '男士长袖衬衫浅蓝色修身商务休闲韩版上班白衬衣',
        price: 49,
        originalPrice: 99,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '浅蓝色',
        style: '韩版',
        season: '四季',
        material: '涤棉',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 45000,
        rating: 4.3,
        tags: ['韩版', '修身', '商务', '便宜'],
        reason: '超高性价比，韩版修身设计，适合预算有限的职场新人。'
    },
    {
        id: 'tb_shirt_004',
        title: 'G2000长袖衬衫男浅蓝色商务修身免烫抗皱职业装',
        price: 229,
        originalPrice: 459,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '浅蓝色',
        style: '职业装',
        season: '四季',
        material: '免烫面料',
        size: ['38', '39', '40', '41', '42'],
        sales: 6700,
        rating: 4.7,
        tags: ['G2000', '职业装', '免烫', '修身'],
        reason: 'G2000专业职业装品牌，版型修身利落，适合金融、法律等专业场合。'
    },
    // 蓝牙耳机
    {
        id: 'tb_earphone_001',
        title: '小米真无线蓝牙耳机Air2 SE 降噪触控超长续航弹窗连接',
        price: 129,
        originalPrice: 169,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 89000,
        rating: 4.6,
        tags: ['小米', '真无线', '降噪', '弹窗'],
        reason: '小米生态链产品，MIUI弹窗连接，20小时综合续航，百元价位优选。'
    },
    {
        id: 'jd_earphone_002',
        title: '华为FreeBuds 4i主动降噪蓝牙耳机入耳式超长续航',
        price: 399,
        originalPrice: 499,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 65000,
        rating: 4.8,
        tags: ['华为', '主动降噪', '入耳式', '长续航'],
        reason: '华为主动降噪技术，10小时单次续航，音质出色，华为主导航优先推荐。'
    },
    {
        id: 'pdd_earphone_003',
        title: '倍思蓝牙耳机真无线降噪入耳式超长续航运动耳机',
        price: 89,
        originalPrice: 159,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1572569028738-411a19723540?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '黑色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 120000,
        rating: 4.5,
        tags: ['倍思', '降噪', '运动', '便宜'],
        reason: '倍思性价比之王，ENC通话降噪，IP55防水适合运动，学生党首选。'
    },
    {
        id: 'tb_earphone_004',
        title: '漫步者LolliPods Pro主动降噪蓝牙耳机入耳式超长续航',
        price: 299,
        originalPrice: 399,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1612444530582-fc66183b16f7?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 34000,
        rating: 4.7,
        tags: ['漫步者', '主动降噪', '入耳式', '音质'],
        reason: '漫步者专业音频品牌，AAC高清解码，-38dB深度降噪，音质出色。'
    },
    {
        id: 'jd_earphone_005',
        title: '索尼WF-1000XM4真无线降噪耳机 蓝牙5.2超长续航',
        price: 1299,
        originalPrice: 1999,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '黑色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 18000,
        rating: 4.9,
        tags: ['索尼', '旗舰', '降噪', '音质'],
        reason: '索尼旗舰降噪豆，行业顶级降噪，LDAC无损音质，预算充足首选。'
    },
    // T恤
    {
        id: 'tb_tshirt_001',
        title: '纯棉白色T恤女短袖宽松百搭夏季基础款圆领内搭',
        price: 39,
        originalPrice: 79,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '白色',
        style: '宽松',
        season: '夏季',
        material: '纯棉',
        size: ['S', 'M', 'L', 'XL'],
        sales: 56000,
        rating: 4.5,
        tags: ['纯棉', '宽松', '百搭', '基础款'],
        reason: '100%纯棉透气舒适，宽松版型不挑身材，基础款万能搭配。'
    },
    {
        id: 'jd_tshirt_002',
        title: '优衣库UT联名T恤男短袖夏季纯棉圆领印花',
        price: 79,
        originalPrice: 99,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '多色',
        style: '印花',
        season: '夏季',
        material: '纯棉',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 78000,
        rating: 4.7,
        tags: ['优衣库', 'UT', '联名', '纯棉'],
        reason: '优衣库UT经典联名款，优质纯棉面料，印花设计时尚百搭。'
    },
    // 连衣裙
    {
        id: 'tb_dress_001',
        title: '法式碎花连衣裙女夏季收腰显瘦气质中长款茶歇裙',
        price: 158,
        originalPrice: 316,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '碎花',
        style: '法式',
        season: '夏季',
        material: '雪纺',
        size: ['S', 'M', 'L', 'XL'],
        sales: 22000,
        rating: 4.6,
        tags: ['法式', '碎花', '收腰', '茶歇裙'],
        reason: '法式茶歇裙经典设计，V领收腰显瘦，碎花浪漫优雅，适合约会出游。'
    },
    {
        id: 'jd_dress_002',
        title: 'ZARA新款吊带连衣裙黑色缎面高级感法式气质长裙',
        price: 299,
        originalPrice: 459,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '黑色',
        style: '吊带',
        season: '夏季',
        material: '缎面',
        size: ['XS', 'S', 'M', 'L'],
        sales: 12000,
        rating: 4.7,
        tags: ['ZARA', '缎面', '高级感', '吊带'],
        reason: 'ZARA缎面面料高级感满满，吊带设计性感优雅，黑色显瘦百搭。'
    },
    // 包包
    {
        id: 'tb_bag_001',
        title: '小ck真皮腋下包女高级感单肩斜挎包春夏新款百搭',
        price: 268,
        originalPrice: 536,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
        category: '包包',
        color: '棕色',
        style: '腋下包',
        season: '春夏',
        material: '真皮',
        size: null,
        sales: 18000,
        rating: 4.6,
        tags: ['小ck', '真皮', '腋下包', '高级感'],
        reason: '小ck经典腋下包款式，真皮材质手感好，百搭棕色适合四季搭配。'
    },
    {
        id: 'jd_bag_002',
        title: '蔻驰COACH托特包大号单肩手提包通勤妈妈包',
        price: 1280,
        originalPrice: 2500,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
        category: '包包',
        color: '棕色',
        style: '托特包',
        season: '四季',
        material: 'PVC/牛皮',
        size: ['大号'],
        sales: 5600,
        rating: 4.8,
        tags: ['COACH', '托特包', '通勤', '品牌'],
        reason: 'COACH经典托特包，大容量适合通勤，品牌保值，自用送礼两相宜。'
    },
    // 手表
    {
        id: 'tb_watch_001',
        title: '卡西欧G-SHOCK运动手表男黑金潮流防水电子表',
        price: 890,
        originalPrice: 1090,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
        category: '手表',
        color: '黑金',
        style: '运动',
        season: null,
        material: '树脂',
        size: null,
        sales: 15000,
        rating: 4.8,
        tags: ['卡西欧', 'G-SHOCK', '黑金', '防水'],
        reason: '卡西欧经典黑金配色，200米防水，耐摔耐用，潮流必备单品。'
    },
    {
        id: 'jd_watch_002',
        title: 'DW手表女简约石英表28mm金色边框白色表盘',
        price: 1180,
        originalPrice: 1490,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400&h=400&fit=crop',
        category: '手表',
        color: '金色',
        style: '简约',
        season: null,
        material: '不锈钢',
        size: ['28mm'],
        sales: 9200,
        rating: 4.7,
        tags: ['DW', '简约', '石英', '轻奢'],
        reason: 'DW北欧简约设计，金色边框优雅精致，适合职场女性日常佩戴。'
    },
    // 护肤套装
    {
        id: 'tb_skincare_001',
        title: 'SK-II神仙水护肤套装神仙水230ml+清莹露+面霜',
        price: 2590,
        originalPrice: 3200,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 28000,
        rating: 4.9,
        tags: ['SK-II', '神仙水', 'Pitera', '套装'],
        reason: 'SK-II王牌Pitera成分，调节水油平衡，提亮肤色，护肤界传奇。'
    },
    {
        id: 'jd_skincare_002',
        title: '兰蔻小黑瓶精华套装肌底液50ml+眼霜+面霜',
        price: 1680,
        originalPrice: 2180,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1570194065650-d99fb4a38b8e?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 18000,
        rating: 4.8,
        tags: ['兰蔻', '小黑瓶', '精华', '抗老'],
        reason: '兰蔻小黑瓶二代精华，Bio-7生物专研配方，修护维稳抗老全能。'
    },
    // 口红
    {
        id: 'tb_lipstick_001',
        title: 'MAC子弹头口红小辣椒chili哑光显白持久不脱色',
        price: 170,
        originalPrice: 185,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop',
        category: '口红',
        color: '小辣椒',
        style: '哑光',
        season: '四季',
        material: null,
        size: ['3g'],
        sales: 95000,
        rating: 4.7,
        tags: ['MAC', '子弹头', 'chili', '显白'],
        reason: 'MAC经典chili小辣椒，黄皮显白神器，哑光质地高级持久。'
    },
    {
        id: 'jd_lipstick_002',
        title: 'YSL小金条口红21号复古正红哑光显白持久',
        price: 335,
        originalPrice: 390,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1591360236480-94955f5209d5?w=400&h=400&fit=crop',
        category: '口红',
        color: '正红',
        style: '哑光',
        season: '四季',
        material: null,
        size: ['2.2g'],
        sales: 45000,
        rating: 4.8,
        tags: ['YSL', '小金条', '正红', '复古'],
        reason: 'YSL小金条21号复古蓝调正红，高级哑光质地，涂上去气场全开。'
    },
    {
        id: 'pdd_lipstick_003',
        title: '完美日记小细跟口红丝绒哑光显白不掉色平价',
        price: 69,
        originalPrice: 129,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?w=400&h=400&fit=crop',
        category: '口红',
        color: '多色',
        style: '丝绒',
        season: '四季',
        material: null,
        size: ['0.8g'],
        sales: 120000,
        rating: 4.5,
        tags: ['完美日记', '小细跟', '丝绒', '平价'],
        reason: '完美日记明星产品，丝绒质地顺滑，平价大牌替代，学生党必入。'
    },
    // 牛仔裤扩充
    {
        id: 'pdd_jeans_007',
        title: '高腰阔腿牛仔裤女春秋新款显瘦垂感黑色宽松直筒裤',
        price: 78,
        originalPrice: 156,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '阔腿',
        season: '春秋',
        material: '牛仔布',
        size: ['S', 'M', 'L', 'XL'],
        sales: 42000,
        rating: 4.4,
        tags: ['高腰', '阔腿', '显瘦', '垂感'],
        reason: '高腰阔腿版型遮肉显瘦，垂感面料柔软舒适，平价好穿。'
    },
    {
        id: 'tb_jeans_008',
        title: '黑色紧身小脚牛仔裤女春秋高腰弹力修身显瘦九分裤',
        price: 99,
        originalPrice: 199,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1485968579169-a6b2e8bb5169?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '修身',
        season: '春秋',
        material: '弹力牛仔',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 28000,
        rating: 4.5,
        tags: ['紧身', '小脚', '弹力', '九分'],
        reason: '紧身小脚版型勾勒腿部线条，弹力面料不勒肉，九分长度显腿长。'
    },
    {
        id: 'jd_jeans_009',
        title: 'Levis李维斯高腰直筒牛仔裤女黑色修身春秋款长裤',
        price: 599,
        originalPrice: 899,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1604176354204-4d9a73dbde9d?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '直筒',
        season: '春秋',
        material: '纯棉牛仔',
        size: ['25', '26', '27', '28', '29', '30'],
        sales: 5600,
        rating: 4.9,
        tags: ['Levis', '高腰', '直筒', '品牌'],
        reason: 'Levis百年牛仔品牌，经典501版型，黑色百搭不过时，品质一流。'
    },
    {
        id: 'tb_jeans_010',
        title: '高腰破洞牛仔裤女春秋黑色宽松直筒裤ins潮显瘦',
        price: 138,
        originalPrice: 276,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1584370848010-d7cc637733f3?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '直筒',
        season: '春秋',
        material: '棉弹牛仔布',
        size: ['S', 'M', 'L'],
        sales: 15000,
        rating: 4.5,
        tags: ['破洞', 'ins', '潮', '直筒'],
        reason: '破洞设计个性潮流，直筒版型修饰腿型，黑色百搭街头风。'
    },
    {
        id: 'pdd_jeans_011',
        title: '微喇牛仔裤女春秋高腰黑色显瘦复古港风拖地长裤',
        price: 68,
        originalPrice: 136,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1584370848010-d7cc637733f3?w=400&h=400&fit=crop',
        category: '牛仔裤',
        color: '黑色',
        style: '微喇',
        season: '春秋',
        material: '弹力牛仔',
        size: ['S', 'M', 'L', 'XL'],
        sales: 32000,
        rating: 4.3,
        tags: ['复古', '港风', '微喇', '拖地'],
        reason: '复古港风微喇设计，拖地长度显腿长，超低价高好评。'
    },
    // 运动鞋扩充
    {
        id: 'tb_shoes_005',
        title: '耐克Air Force 1小白鞋男空军一号经典板鞋白色',
        price: 749,
        originalPrice: 899,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '休闲',
        season: '四季',
        material: '皮革',
        size: ['39', '40', '41', '42', '43', '44'],
        sales: 32000,
        rating: 4.8,
        tags: ['耐克', 'AF1', '经典', '板鞋'],
        reason: 'Nike AF1经典永不过时，全白配色百搭神器，空军一号街头标杆。'
    },
    {
        id: 'jd_shoes_006',
        title: 'New Balance 574复古跑鞋男夏季透气网面运动鞋灰色',
        price: 459,
        originalPrice: 599,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '灰色',
        style: '休闲',
        season: '夏季',
        material: '网面',
        size: ['36', '37', '38', '39', '40', '41', '42', '43'],
        sales: 18000,
        rating: 4.7,
        tags: ['NB', '574', '复古', '经典'],
        reason: 'NB 574经典复古跑鞋，ENCAP缓震科技，灰色低调百搭，日常通勤首选。'
    },
    {
        id: 'pdd_shoes_007',
        title: '鸿星尔克运动鞋男夏季透气网面跑步鞋轻便减震',
        price: 129,
        originalPrice: 259,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '黑色',
        style: '跑步',
        season: '夏季',
        material: '网面',
        size: ['39', '40', '41', '42', '43', '44'],
        sales: 56000,
        rating: 4.6,
        tags: ['鸿星尔克', '国货', '透气', '跑步'],
        reason: '鸿星尔克国货之光，夏季透气网面不闷脚，轻便减震适合日常跑步。'
    },
    {
        id: 'tb_shoes_008',
        title: '亚瑟士GEL-CONTEND 4跑步鞋男夏季透气减震运动鞋',
        price: 369,
        originalPrice: 490,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '跑步',
        season: '夏季',
        material: '网面',
        size: ['39', '40', '41', '42', '43', '44'],
        sales: 12000,
        rating: 4.8,
        tags: ['亚瑟士', 'GEL', '减震', '专业'],
        reason: '亚瑟士GEL缓震科技，专业跑步设计，透气网面夏季不闷脚，脚感出色。'
    },
    {
        id: 'jd_shoes_009',
        title: '李宁超轻19跑步鞋男夏季透气网面运动鞋黑色',
        price: 398,
        originalPrice: 599,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '黑色',
        style: '跑步',
        season: '夏季',
        material: '网面',
        size: ['39', '40', '41', '42', '43', '44'],
        sales: 25000,
        rating: 4.7,
        tags: ['李宁', '超轻', '透气', '国货'],
        reason: '李宁超轻19代，轻量透气设计，国产跑鞋代表作，夏季跑步首选。'
    },
    {
        id: 'tb_shoes_010',
        title: '阿迪达斯Stan Smith绿尾小白鞋男女经典板鞋休闲',
        price: 499,
        originalPrice: 799,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop',
        category: '运动鞋',
        color: '白色',
        style: '休闲',
        season: '四季',
        material: '皮革',
        size: ['36', '37', '38', '39', '40', '41', '42', '43'],
        sales: 22000,
        rating: 4.7,
        tags: ['阿迪达斯', '绿尾', '经典', '小白鞋'],
        reason: '阿迪达斯绿尾经典板鞋，简约百搭，皮革鞋面质感好，时尚永不过时。'
    },
    // 面霜扩充
    {
        id: 'jd_face_006',
        title: '科颜氏高保湿面霜50ml 干皮救星深层补水滋润',
        price: 315,
        originalPrice: 390,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['50ml'],
        sales: 85000,
        rating: 4.8,
        tags: ['科颜氏', '高保湿', '干皮', '补水'],
        reason: '科颜氏高保湿面霜，南极冰川蛋白深层补水，干皮救星，秋冬必备。'
    },
    {
        id: 'tb_face_007',
        title: '玉泽皮肤屏障修护保湿霜50g 敏感肌适用补水',
        price: 158,
        originalPrice: 228,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['50g'],
        sales: 32000,
        rating: 4.7,
        tags: ['玉泽', '屏障修护', '敏感肌', '国货'],
        reason: '玉泽屏障修护系列，PBS植物仿生脂质技术，医院皮肤科推荐品牌。'
    },
    {
        id: 'pdd_face_008',
        title: '启初婴儿多效倍润面霜40g 温和保湿滋润敏感肌可用',
        price: 35,
        originalPrice: 58,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['40g'],
        sales: 68000,
        rating: 4.6,
        tags: ['启初', '婴儿', '温和', '平价'],
        reason: '启初婴儿面霜，胚米精华温和保湿，成人敏感肌也可用，超高性价比。'
    },
    {
        id: 'tb_face_009',
        title: '海蓝之谜精华面霜30ml 修护抗老奢华滋润',
        price: 1520,
        originalPrice: 1900,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1570194065650-d99fb4a38b8e?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['30ml'],
        sales: 12000,
        rating: 4.9,
        tags: ['海蓝之谜', '奢华', '修护', '抗老'],
        reason: 'La Mer传奇精华面霜，神奇活性精萃Miracle Broth，修护抗老天花板。'
    },
    {
        id: 'jd_face_010',
        title: '适乐肤C霜修护保湿面霜340g 神经酰胺敏感肌大容量',
        price: 98,
        originalPrice: 168,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop',
        category: '面霜',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['340g'],
        sales: 45000,
        rating: 4.7,
        tags: ['适乐肤', 'C霜', '神经酰胺', '大容量'],
        reason: '适乐肤C霜，三重神经酰胺修护屏障，340g大容量全家可用，平价大碗。'
    },
    // 衬衫扩充
    {
        id: 'pdd_shirt_005',
        title: '男士白衬衫长袖商务正装免烫修身职业上班工装',
        price: 39,
        originalPrice: 79,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '白色',
        style: '商务正装',
        season: '四季',
        material: '涤棉',
        size: ['M', 'L', 'XL', 'XXL', 'XXXL'],
        sales: 38000,
        rating: 4.3,
        tags: ['白衬衫', '正装', '免烫', '工装'],
        reason: '经典白衬衫商务必备，免烫面料省心打理，超大码可选，性价比极高。'
    },
    {
        id: 'tb_shirt_006',
        title: 'UNIQLO优衣库法兰绒格子衬衫男长袖休闲春秋',
        price: 99,
        originalPrice: 149,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '多色',
        style: '休闲',
        season: '春秋',
        material: '法兰绒',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 52000,
        rating: 4.7,
        tags: ['优衣库', '法兰绒', '格子', '休闲'],
        reason: '优衣库经典法兰绒衬衫，柔软亲肤，格子图案百搭，春秋外穿内搭皆可。'
    },
    {
        id: 'jd_shirt_007',
        title: '七匹狼长袖衬衫男商务休闲纯棉条纹中年爸爸装',
        price: 179,
        originalPrice: 359,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '蓝色',
        style: '商务休闲',
        season: '四季',
        material: '纯棉',
        size: ['38', '39', '40', '41', '42', '43'],
        sales: 15000,
        rating: 4.6,
        tags: ['七匹狼', '条纹', '中年', '纯棉'],
        reason: '七匹狼商务经典，纯棉条纹设计，适合中年男士商务休闲场合。'
    },
    {
        id: 'tb_shirt_008',
        title: '牛津纺白衬衫女长袖通勤面试职业正装宽松百搭',
        price: 89,
        originalPrice: 179,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '白色',
        style: '职业装',
        season: '四季',
        material: '牛津纺',
        size: ['S', 'M', 'L', 'XL'],
        sales: 22000,
        rating: 4.5,
        tags: ['牛津纺', '通勤', '面试', '职业'],
        reason: '牛津纺面料挺括有型，宽松版型不挑身材，面试通勤首选白衬衫。'
    },
    {
        id: 'pdd_shirt_009',
        title: '牛仔衬衫男长袖春秋休闲宽松韩版潮流外套衬衣',
        price: 45,
        originalPrice: 89,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1604176354204-4d9a73dbde9d?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '蓝色',
        style: '休闲',
        season: '春秋',
        material: '牛仔',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 28000,
        rating: 4.3,
        tags: ['牛仔', '韩版', '潮流', '外套'],
        reason: '牛仔衬衫可当外套穿，韩版宽松潮流设计，春秋叠穿神器。'
    },
    {
        id: 'tb_shirt_010',
        title: '法式复古灯笼袖衬衫女设计感小众上衣春秋',
        price: 128,
        originalPrice: 256,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
        category: '衬衫',
        color: '白色',
        style: '法式',
        season: '春秋',
        material: '棉',
        size: ['S', 'M', 'L'],
        sales: 18000,
        rating: 4.6,
        tags: ['法式', '灯笼袖', '设计感', '小众'],
        reason: '法式复古灯笼袖设计，小众不撞衫，温柔优雅，春秋单穿绝美。'
    },
    // 蓝牙耳机扩充
    {
        id: 'tb_earphone_006',
        title: 'AirPods Pro 2代主动降噪蓝牙耳机苹果原装',
        price: 1899,
        originalPrice: 2299,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 45000,
        rating: 4.9,
        tags: ['苹果', 'AirPods', '主动降噪', '原装'],
        reason: '苹果AirPods Pro 2代，H2芯片主动降噪，空间音频，苹果用户首选。'
    },
    {
        id: 'jd_earphone_007',
        title: 'JBL TUNE 760NC头戴式蓝牙耳机主动降噪无线耳麦',
        price: 599,
        originalPrice: 799,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '黑色',
        style: '头戴式',
        season: null,
        material: null,
        size: null,
        sales: 12000,
        rating: 4.6,
        tags: ['JBL', '头戴式', '主动降噪', '耳麦'],
        reason: 'JBL头戴式降噪耳机，Pure Bass低音强劲，佩戴舒适，通勤学习好伴侣。'
    },
    {
        id: 'pdd_earphone_008',
        title: 'QCY T13真无线蓝牙耳机入耳式超长续航高清通话',
        price: 79,
        originalPrice: 129,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 85000,
        rating: 4.5,
        tags: ['QCY', '真无线', '高清通话', '平价'],
        reason: 'QCY百元内真无线耳机标杆，蓝牙5.1稳定连接，40小时超长续航。'
    },
    {
        id: 'tb_earphone_009',
        title: '铁三角ATH-M50x专业监听头戴式耳机有线蓝牙两用',
        price: 1199,
        originalPrice: 1499,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1612444530582-fc66183b16f7?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '黑色',
        style: '头戴式',
        season: null,
        material: null,
        size: null,
        sales: 8000,
        rating: 4.8,
        tags: ['铁三角', '监听', '专业', '有线'],
        reason: '铁三角M50x专业监听耳机，45mm大驱动单元，录音棚级音质，音乐人首选。'
    },
    {
        id: 'jd_earphone_010',
        title: '三星Galaxy Buds2 Pro主动降噪真无线蓝牙耳机',
        price: 899,
        originalPrice: 1299,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1572569028738-411a19723540?w=400&h=400&fit=crop',
        category: '蓝牙耳机',
        color: '白色',
        style: '入耳式',
        season: null,
        material: null,
        size: null,
        sales: 15000,
        rating: 4.7,
        tags: ['三星', 'Galaxy', '主动降噪', '24bit'],
        reason: '三星Galaxy Buds2 Pro，24bit高保真音频，360音频空间感，安卓旗舰配塞。'
    },
    // T恤扩充
    {
        id: 'pdd_tshirt_003',
        title: '纯色纯棉短袖T恤男夏季圆领宽松百搭半袖上衣',
        price: 19,
        originalPrice: 39,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '白色',
        style: '宽松',
        season: '夏季',
        material: '纯棉',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 120000,
        rating: 4.3,
        tags: ['纯色', '纯棉', '宽松', '平价'],
        reason: '19元纯棉T恤性价比之王，基础纯色百搭，夏季多囤几件不心疼。'
    },
    {
        id: 'tb_tshirt_004',
        title: 'BM风短款露脐T恤女夏季修身显瘦高腰短袖上衣',
        price: 59,
        originalPrice: 119,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '白色',
        style: '修身',
        season: '夏季',
        material: '棉',
        size: ['S', 'M', 'L'],
        sales: 45000,
        rating: 4.5,
        tags: ['BM', '短款', '露脐', '修身'],
        reason: 'BM风短款露脐设计，配高腰裤显腿长，修身版型凸显身材曲线。'
    },
    {
        id: 'jd_tshirt_005',
        title: '李宁运动T恤男夏季速干透气跑步健身短袖黑色',
        price: 89,
        originalPrice: 139,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '黑色',
        style: '运动',
        season: '夏季',
        material: '速干',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 35000,
        rating: 4.6,
        tags: ['李宁', '速干', '运动', '透气'],
        reason: '李宁速干运动T恤，AT DRY速干科技，跑步健身不黏身，国货运动首选。'
    },
    {
        id: 'tb_tshirt_006',
        title: 'oversize宽松大码T恤男女夏季纯棉潮流印花半袖',
        price: 69,
        originalPrice: 138,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '黑色',
        style: '宽松',
        season: '夏季',
        material: '纯棉',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 28000,
        rating: 4.4,
        tags: ['oversize', '大码', '潮流', '印花'],
        reason: 'oversize宽松版型男女同款，潮流印花设计，街头风十足，遮肉显瘦。'
    },
    {
        id: 'pdd_tshirt_007',
        title: '莫代尔冰丝短袖T恤男夏季薄款透气凉感半袖',
        price: 29,
        originalPrice: 59,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '白色',
        style: '宽松',
        season: '夏季',
        material: '莫代尔',
        size: ['M', 'L', 'XL', 'XXL', 'XXXL'],
        sales: 68000,
        rating: 4.3,
        tags: ['莫代尔', '冰丝', '凉感', '薄款'],
        reason: '莫代尔冰丝面料轻薄透气，凉感科技夏季不闷热，大码可选。'
    },
    {
        id: 'tb_tshirt_008',
        title: '拉夫劳伦小马标Polo衫男夏季纯棉修身短袖T恤',
        price: 890,
        originalPrice: 1290,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&h=400&fit=crop',
        category: 'T恤',
        color: '多色',
        style: '商务休闲',
        season: '夏季',
        material: '纯棉',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 15000,
        rating: 4.8,
        tags: ['拉夫劳伦', 'Polo', '小马标', '商务'],
        reason: 'Ralph Lauren经典小马标Polo衫，珠地棉透气修身，商务休闲两相宜。'
    },
    // 连衣裙扩充
    {
        id: 'pdd_dress_003',
        title: '白色初恋连衣裙女夏季收腰显瘦法式小白裙',
        price: 59,
        originalPrice: 119,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '白色',
        style: '法式',
        season: '夏季',
        material: '棉',
        size: ['S', 'M', 'L', 'XL'],
        sales: 38000,
        rating: 4.4,
        tags: ['初恋', '小白裙', '法式', '收腰'],
        reason: '白色初恋感连衣裙，法式收腰设计清新优雅，约会出游拍照绝配。'
    },
    {
        id: 'tb_dress_004',
        title: '复古波点连衣裙女夏季收腰显瘦中长款茶歇裙',
        price: 178,
        originalPrice: 356,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '黑色',
        style: '法式',
        season: '夏季',
        material: '雪纺',
        size: ['S', 'M', 'L'],
        sales: 22000,
        rating: 4.6,
        tags: ['复古', '波点', '茶歇裙', '收腰'],
        reason: '复古波点元素永不过时，茶歇裙收腰显瘦，中长款优雅得体。'
    },
    {
        id: 'jd_dress_005',
        title: 'UR夏季新款吊带碎花连衣裙女法式气质长裙',
        price: 269,
        originalPrice: 399,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '碎花',
        style: '吊带',
        season: '夏季',
        material: '雪纺',
        size: ['XS', 'S', 'M', 'L'],
        sales: 16000,
        rating: 4.5,
        tags: ['UR', '碎花', '吊带', '气质'],
        reason: 'UR当季新款，碎花吊带长裙温柔浪漫，法式气质满满，度假必备。'
    },
    {
        id: 'tb_dress_006',
        title: '学院风JK制服连衣裙女夏季百褶短裙套装',
        price: 128,
        originalPrice: 258,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1495385794356-15371f348c31?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '蓝色',
        style: '韩版',
        season: '夏季',
        material: '涤纶',
        size: ['S', 'M', 'L'],
        sales: 45000,
        rating: 4.5,
        tags: ['JK', '学院风', '百褶', '制服'],
        reason: '学院风JK制服连衣裙，减龄百褶设计，校园感满满，二次元必备。'
    },
    {
        id: 'pdd_dress_007',
        title: '真丝连衣裙女夏季高端桑蚕丝印花中长款妈妈装',
        price: 199,
        originalPrice: 399,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '碎花',
        style: '简约',
        season: '夏季',
        material: '真丝',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 12000,
        rating: 4.4,
        tags: ['真丝', '桑蚕丝', '高端', '妈妈装'],
        reason: '真丝桑蚕丝面料亲肤透气，印花设计优雅大方，适合妈妈辈日常穿搭。'
    },
    {
        id: 'tb_dress_008',
        title: '赫本风小黑裙女夏季显瘦收腰A字连衣裙气质',
        price: 168,
        originalPrice: 336,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
        category: '连衣裙',
        color: '黑色',
        style: '简约',
        season: '夏季',
        material: '棉',
        size: ['S', 'M', 'L', 'XL'],
        sales: 25000,
        rating: 4.7,
        tags: ['赫本风', '小黑裙', 'A字', '气质'],
        reason: '经典赫本风小黑裙，A字版型遮胯显瘦，黑色永不过时，气质女神必备。'
    },
    // 包包扩充
    {
        id: 'pdd_bag_003',
        title: '尼龙防水单肩包女大容量通勤托特包百搭上课包',
        price: 29,
        originalPrice: 59,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
        category: '包包',
        color: '黑色',
        style: '托特包',
        season: '四季',
        material: '尼龙',
        size: ['大号'],
        sales: 85000,
        rating: 4.4,
        tags: ['尼龙', '防水', '大容量', '通勤'],
        reason: '尼龙防水材质轻便耐用，大容量适合通勤上课，29元性价比之王。'
    },
    {
        id: 'tb_bag_004',
        title: 'MCM经典铆钉双肩包中号棕色大容量旅行背包',
        price: 3580,
        originalPrice: 5200,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
        category: '包包',
        color: '棕色',
        style: '托特包',
        season: '四季',
        material: 'PVC',
        size: ['中号'],
        sales: 3200,
        rating: 4.8,
        tags: ['MCM', '铆钉', '双肩包', '品牌'],
        reason: 'MCM经典Visetos老花铆钉双肩包，品牌辨识度高，大容量旅行通勤皆可。'
    },
    {
        id: 'jd_bag_005',
        title: ' Longchamp龙骧饺子包大号长柄单肩包通勤尼龙',
        price: 850,
        originalPrice: 1100,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
        category: '包包',
        color: '多色',
        style: '托特包',
        season: '四季',
        material: '尼龙',
        size: ['大号'],
        sales: 18000,
        rating: 4.7,
        tags: ['Longchamp', '饺子包', '通勤', '轻便'],
        reason: 'Longchamp经典饺子包，尼龙轻便防水可折叠，通勤旅行万能包。'
    },
    {
        id: 'tb_bag_006',
        title: '剑桥包小号复古英伦风斜挎包女学院风百搭',
        price: 158,
        originalPrice: 316,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&h=400&fit=crop',
        category: '包包',
        color: '棕色',
        style: '托特包',
        season: '四季',
        material: 'PU',
        size: ['小号'],
        sales: 12000,
        rating: 4.5,
        tags: ['剑桥包', '复古', '英伦', '学院风'],
        reason: '复古剑桥包经典英伦学院风，小号斜挎精致可爱，百搭又减龄。'
    },
    {
        id: 'pdd_bag_007',
        title: '帆布包女大容量单肩包文艺日系百搭环保袋',
        price: 15,
        originalPrice: 29,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
        category: '包包',
        color: '多色',
        style: '托特包',
        season: '四季',
        material: '帆布',
        size: ['大号'],
        sales: 95000,
        rating: 4.3,
        tags: ['帆布', '文艺', '环保', '大容量'],
        reason: '帆布包文艺日系风，超大容量装书装电脑，15元环保又实用。'
    },
    {
        id: 'tb_bag_008',
        title: 'LV Neverfull中号老花托特包单肩手提包',
        price: 12800,
        originalPrice: 14500,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
        category: '包包',
        color: '棕色',
        style: '托特包',
        season: '四季',
        material: 'PVC',
        size: ['中号'],
        sales: 8000,
        rating: 4.9,
        tags: ['LV', 'Neverfull', '老花', '奢侈品'],
        reason: 'LV经典Neverfull托特包，Monogram老花保值，中号容量适中，入门首选。'
    },
    // 手表扩充
    {
        id: 'jd_watch_003',
        title: '天梭力洛克机械男表经典罗马刻度皮带腕表',
        price: 3250,
        originalPrice: 4350,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
        category: '手表',
        color: '黑色',
        style: '商务',
        season: null,
        material: '不锈钢',
        size: ['39mm'],
        sales: 8500,
        rating: 4.8,
        tags: ['天梭', '力洛克', '机械表', '商务'],
        reason: '天梭力洛克经典机械表，瑞士ETA机芯，罗马刻度皮带优雅商务。'
    },
    {
        id: 'tb_watch_004',
        title: 'Apple Watch Series 9智能手表GPS款星光色',
        price: 2999,
        originalPrice: 3199,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1434494878577-86c23db18b5c?w=400&h=400&fit=crop',
        category: '手表',
        color: '金色',
        style: '简约',
        season: null,
        material: '铝金属',
        size: ['41mm'],
        sales: 28000,
        rating: 4.9,
        tags: ['苹果', 'AppleWatch', '智能', '运动'],
        reason: 'Apple Watch S9全新S9芯片，健康监测运动追踪，苹果生态完美联动。'
    },
    {
        id: 'pdd_watch_005',
        title: '小米手环8智能运动手环血氧心率监测长续航',
        price: 199,
        originalPrice: 249,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&h=400&fit=crop',
        category: '手表',
        color: '黑色',
        style: '运动',
        season: null,
        material: '硅胶',
        size: null,
        sales: 120000,
        rating: 4.6,
        tags: ['小米', '手环', '血氧', '运动'],
        reason: '小米手环8代，150+运动模式，血氧心率监测，14天超长续航，性价比之王。'
    },
    {
        id: 'tb_watch_006',
        title: '浪琴名匠系列机械男表蓝针皮带经典商务腕表',
        price: 15800,
        originalPrice: 18200,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400&h=400&fit=crop',
        category: '手表',
        color: '棕色',
        style: '商务',
        season: null,
        material: '不锈钢',
        size: ['38.5mm'],
        sales: 4500,
        rating: 4.9,
        tags: ['浪琴', '名匠', '机械表', '蓝针'],
        reason: '浪琴名匠系列经典蓝针，鳄鱼皮表带质感奢华，商务精英首选。'
    },
    {
        id: 'jd_watch_007',
        title: '华为Watch GT4智能手表蓝牙通话健康监测黑色',
        price: 1388,
        originalPrice: 1688,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
        category: '手表',
        color: '黑色',
        style: '简约',
        season: null,
        material: '不锈钢',
        size: ['46mm'],
        sales: 22000,
        rating: 4.8,
        tags: ['华为', 'GT4', '蓝牙通话', '健康'],
        reason: '华为Watch GT4，14天超长续航，蓝牙通话，全面健康监测，安卓用户首选。'
    },
    {
        id: 'tb_watch_008',
        title: '卡西欧小方块电子表男经典复古黑色防水',
        price: 280,
        originalPrice: 390,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
        category: '手表',
        color: '黑色',
        style: '简约',
        season: null,
        material: '树脂',
        size: null,
        sales: 35000,
        rating: 4.7,
        tags: ['卡西欧', '小方块', '复古', '防水'],
        reason: '卡西欧小方块经典电子表，复古百搭，10年电池寿命，学生党必备。'
    },
    // 护肤套装扩充
    {
        id: 'pdd_skincare_003',
        title: '珀莱雅双抗精华套装抗糖抗氧化提亮肤色水乳',
        price: 299,
        originalPrice: 459,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 45000,
        rating: 4.7,
        tags: ['珀莱雅', '双抗', '抗糖', '提亮'],
        reason: '珀莱雅双抗系列，抗糖抗氧化双效合一，提亮肤色改善暗沉，国货爆款。'
    },
    {
        id: 'tb_skincare_004',
        title: '雅诗兰黛小棕瓶精华套装50ml眼霜面霜抗老',
        price: 1580,
        originalPrice: 2100,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1570194065650-d99fb4a38b8e?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 22000,
        rating: 4.9,
        tags: ['雅诗兰黛', '小棕瓶', '抗老', '精华'],
        reason: '雅诗兰黛第七代小棕瓶，Chronolux Power Signal科技，夜间修护抗老标杆。'
    },
    {
        id: 'jd_skincare_005',
        title: '欧莱雅复颜抗皱套装水乳面霜紧致抗老妈妈护肤',
        price: 369,
        originalPrice: 529,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 38000,
        rating: 4.6,
        tags: ['欧莱雅', '复颜', '抗皱', '妈妈'],
        reason: '欧莱雅复颜抗皱系列，视黄醇PRO紧致淡纹，妈妈辈抗老护肤首选。'
    },
    {
        id: 'tb_skincare_006',
        title: '后Whoo天气丹花献光彩紧颜套装礼盒抗老滋养',
        price: 1380,
        originalPrice: 1660,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 15000,
        rating: 4.8,
        tags: ['后', '天气丹', '韩方', '滋养'],
        reason: 'Whoo天气丹花献系列，山参鹿茸珍贵成分，全效抗老滋养，韩国宫廷配方。'
    },
    {
        id: 'pdd_skincare_007',
        title: '百雀羚肌初赋活套装水乳面霜抗皱紧致妈妈护肤',
        price: 198,
        originalPrice: 298,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 32000,
        rating: 4.5,
        tags: ['百雀羚', '肌初赋活', '国货', '妈妈'],
        reason: '百雀羚经典国货，草本精华温和抗皱，妈妈辈信赖品牌，礼盒装送礼体面。'
    },
    {
        id: 'tb_skincare_008',
        title: '资生堂悦薇珀翡水乳套装抗老提亮紧致肌肤',
        price: 1080,
        originalPrice: 1440,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
        category: '护肤套装',
        color: null,
        style: null,
        season: '四季',
        material: null,
        size: ['套装'],
        sales: 18000,
        rating: 4.8,
        tags: ['资生堂', '悦薇', '抗老', '提亮'],
        reason: '资生堂悦薇珀翡系列，VP8复合植萃，抗老提亮双效，亚洲肌肤专研。'
    },
    // 口红扩充
    {
        id: 'tb_lipstick_004',
        title: '迪奥999哑光正红口红经典显白滋润不拔干',
        price: 370,
        originalPrice: 390,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop',
        category: '口红',
        color: '正红',
        style: '哑光',
        season: '四季',
        material: null,
        size: ['3.5g'],
        sales: 65000,
        rating: 4.8,
        tags: ['迪奥', '999', '正红', '经典'],
        reason: 'Dior 999传奇正红，每个女人都该拥有一支，哑光高级不拔干，显白王者。'
    },
    {
        id: 'jd_lipstick_005',
        title: '阿玛尼红管唇釉405烂番茄色丝绒哑光显白',
        price: 310,
        originalPrice: 350,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1591360236480-94955f5209d5?w=400&h=400&fit=crop',
        category: '口红',
        color: '红色',
        style: '丝绒',
        season: '四季',
        material: null,
        size: ['6.5ml'],
        sales: 52000,
        rating: 4.9,
        tags: ['阿玛尼', '红管', '405', '烂番茄'],
        reason: '阿玛尼红管405烂番茄色鼻祖，丝绒质地显白不挑皮，黄皮亲妈。'
    },
    {
        id: 'pdd_lipstick_006',
        title: 'Colorkey珂拉琪唇釉丝绒哑光平价学生显白',
        price: 29,
        originalPrice: 59,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?w=400&h=400&fit=crop',
        category: '口红',
        color: '多色',
        style: '丝绒',
        season: '四季',
        material: null,
        size: ['1.7g'],
        sales: 150000,
        rating: 4.5,
        tags: ['Colorkey', '珂拉琪', '平价', '学生'],
        reason: 'Colorkey空气唇釉，轻薄丝绒质地，29元国货之光，学生党闭眼入。'
    },
    {
        id: 'tb_lipstick_007',
        title: '香奈儿58号 Rouge Allure Velvet 丝绒红棕色',
        price: 380,
        originalPrice: 390,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop',
        category: '口红',
        color: '棕色',
        style: '丝绒',
        season: '四季',
        material: null,
        size: ['3.5g'],
        sales: 28000,
        rating: 4.8,
        tags: ['香奈儿', '58', '红棕', '秋冬'],
        reason: 'Chanel 58经典红棕色，丝绒质地高级，秋冬氛围感拉满，气质女神色。'
    },
    {
        id: 'jd_lipstick_008',
        title: '兰蔻196胡萝卜色丝绒哑光口红显白持久',
        price: 285,
        originalPrice: 320,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1591360236480-94955f5209d5?w=400&h=400&fit=crop',
        category: '口红',
        color: '红色',
        style: '哑光',
        season: '四季',
        material: null,
        size: ['3.4g'],
        sales: 42000,
        rating: 4.8,
        tags: ['兰蔻', '196', '胡萝卜', '显白'],
        reason: '兰蔻196胡萝卜色，元气显白不挑皮，哑光质地高级持久，断货王。'
    },
    {
        id: 'pdd_lipstick_009',
        title: '花西子雕花口红丝绒哑光中国风复古番茄红',
        price: 89,
        originalPrice: 129,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?w=400&h=400&fit=crop',
        category: '口红',
        color: '红色',
        style: '丝绒',
        season: '四季',
        material: null,
        size: ['3.2g'],
        sales: 68000,
        rating: 4.6,
        tags: ['花西子', '雕花', '中国风', '国货'],
        reason: '花西子雕花口红，微雕工艺精美绝伦，中国风包装送礼佳品，国货骄傲。'
    },
    // 新增类别 - 卫衣
    {
        id: 'tb_hoodie_001',
        title: '连帽卫衣男春秋纯棉宽松百搭纯色套头上衣',
        price: 89,
        originalPrice: 179,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400&h=400&fit=crop',
        category: '卫衣',
        color: '黑色',
        style: '宽松',
        season: '春秋',
        material: '纯棉',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 32000,
        rating: 4.5,
        tags: ['连帽', '纯棉', '宽松', '纯色'],
        reason: '纯棉连帽卫衣，宽松版型遮肉显瘦，纯色百搭春秋必备单品。'
    },
    {
        id: 'jd_hoodie_002',
        title: 'Champion冠军卫衣女圆领刺绣logo春秋薄款',
        price: 289,
        originalPrice: 459,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=400&h=400&fit=crop',
        category: '卫衣',
        color: '灰色',
        style: '休闲',
        season: '春秋',
        material: '棉',
        size: ['S', 'M', 'L', 'XL'],
        sales: 18000,
        rating: 4.7,
        tags: ['Champion', '冠军', '刺绣', '经典'],
        reason: 'Champion经典草写刺绣卫衣，美式街头风格，品牌辨识度极高。'
    },
    {
        id: 'pdd_hoodie_003',
        title: '加绒加厚卫衣女冬季保暖宽松韩版ins潮',
        price: 49,
        originalPrice: 99,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop',
        category: '卫衣',
        color: '白色',
        style: '韩版',
        season: '冬季',
        material: '加绒',
        size: ['S', 'M', 'L', 'XL'],
        sales: 45000,
        rating: 4.4,
        tags: ['加绒', '加厚', '保暖', '韩版'],
        reason: '内里加绒加厚保暖，宽松韩版版型，冬季内搭外穿皆可，性价比超高。'
    },
    {
        id: 'tb_hoodie_004',
        title: 'NASA联名宇航员卫衣男春秋潮牌印花宽松',
        price: 128,
        originalPrice: 256,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400&h=400&fit=crop',
        category: '卫衣',
        color: '黑色',
        style: '宽松',
        season: '春秋',
        material: '棉',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 25000,
        rating: 4.5,
        tags: ['NASA', '宇航员', '潮牌', '联名'],
        reason: 'NASA联名宇航员印花卫衣，潮牌设计个性十足，宽松版型男女同款。'
    },
    {
        id: 'jd_hoodie_005',
        title: 'Nike耐克卫衣男连帽运动休闲套头衫春秋黑色',
        price: 349,
        originalPrice: 499,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=400&h=400&fit=crop',
        category: '卫衣',
        color: '黑色',
        style: '运动',
        season: '春秋',
        material: '棉',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 22000,
        rating: 4.7,
        tags: ['耐克', '连帽', '运动', '品牌'],
        reason: 'Nike经典连帽卫衣，运动休闲两相宜，黑色百搭，品牌品质有保障。'
    },
    // 新增类别 - 外套
    {
        id: 'tb_jacket_001',
        title: '牛仔外套女春秋宽松韩版bf风短款夹克上衣',
        price: 138,
        originalPrice: 276,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=400&h=400&fit=crop',
        category: '外套',
        color: '蓝色',
        style: '宽松',
        season: '春秋',
        material: '牛仔',
        size: ['S', 'M', 'L', 'XL'],
        sales: 28000,
        rating: 4.5,
        tags: ['牛仔', 'bf风', '短款', '韩版'],
        reason: '经典牛仔外套，bf风宽松版型，春秋外穿百搭，永不过时的单品。'
    },
    {
        id: 'jd_jacket_002',
        title: '北面The North Face冲锋衣男户外防水防风外套',
        price: 1298,
        originalPrice: 1698,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400&h=400&fit=crop',
        category: '外套',
        color: '黑色',
        style: '运动',
        season: '春秋',
        material: '尼龙',
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        sales: 15000,
        rating: 4.8,
        tags: ['北面', '冲锋衣', '防水', '户外'],
        reason: 'The North Face经典冲锋衣，DryVent防水透气，户外旅行必备装备。'
    },
    {
        id: 'pdd_jacket_003',
        title: '小西装外套女春秋韩版修身短款职业西服',
        price: 79,
        originalPrice: 159,
        platform: 'pdd',
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
        category: '外套',
        color: '黑色',
        style: '商务',
        season: '春秋',
        material: '涤纶',
        size: ['S', 'M', 'L', 'XL'],
        sales: 38000,
        rating: 4.3,
        tags: ['小西装', '修身', '职业', '韩版'],
        reason: '韩版修身小西装，短款显腿长，职场面试通勤皆可，平价好品质。'
    },
    {
        id: 'tb_jacket_004',
        title: '优衣库摇粒绒外套女秋冬保暖轻便抓绒夹克',
        price: 149,
        originalPrice: 199,
        platform: 'taobao',
        image: 'https://images.unsplash.com/photo-1551488852-0801751ac367?w=400&h=400&fit=crop',
        category: '外套',
        color: '棕色',
        style: '休闲',
        season: '冬季',
        material: '摇粒绒',
        size: ['S', 'M', 'L', 'XL'],
        sales: 42000,
        rating: 4.7,
        tags: ['优衣库', '摇粒绒', '保暖', '轻便'],
        reason: '优衣库经典摇粒绒外套，轻便保暖，棕色温柔百搭，秋冬居家外出皆宜。'
    },
    {
        id: 'jd_jacket_005',
        title: '飞行员夹克MA-1空军外套男春秋韩版潮流',
        price: 198,
        originalPrice: 398,
        platform: 'jd',
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
        category: '外套',
        color: '绿色',
        style: '休闲',
        season: '春秋',
        material: '尼龙',
        size: ['M', 'L', 'XL', 'XXL'],
        sales: 18000,
        rating: 4.5,
        tags: ['MA-1', '飞行员', '夹克', '潮流'],
        reason: 'MA-1经典飞行员夹克，军绿色潮流复古，男女同款，春秋外穿帅气十足。'
    }
];

// Platform names mapping
const PLATFORM_NAMES = {
    taobao: '淘宝',
    jd: '京东',
    pdd: '拼多多'
};

// Known brands for precise search
const KNOWN_BRANDS = [
    'ONLY', 'Lee', 'Levis', '李维斯', 'Nike', '耐克', '安踏', '回力', '特步',
    '华为', '小米', '索尼', '优衣库', 'UNIQLO', 'ZARA', 'G2000', 'COACH', '蔻驰',
    'MCM', 'LV', 'Longchamp', '龙骧', 'DW', '卡西欧', 'Apple', '天梭', '浪琴',
    'SK-II', '兰蔻', '雅诗兰黛', '迪奥', 'Dior', 'YSL', '圣罗兰', '阿玛尼', '香奈儿', 'Chanel',
    'MAC', 'FAB', '珂润', '理肤泉', '薇诺娜', '丝塔芙', '科颜氏', '玉泽', '启初',
    '海蓝之谜', '适乐肤', '雅戈尔', '七匹狼', 'Champion', 'NASA', 'JBL', 'QCY',
    '铁三角', '三星', 'Galaxy', 'New Balance', 'NB', '鸿星尔克', '亚瑟士', '李宁',
    '阿迪达斯', 'Adidas', 'AirPods', '珀莱雅', '欧莱雅', '百雀羚', '资生堂',
    '后', 'Whoo', 'Colorkey', '珂拉琪', '花西子', '完美日记', '拉夫劳伦',
    'Ralph Lauren', '北面', 'The North Face', 'UR', 'Vans', '匡威', 'Converse',
    '安踏', '特步', '鸿星尔克', '匹克', '361度', '乔丹', '回力', '飞跃'
];

function extractBrand(title) {
    for (const brand of KNOWN_BRANDS) {
        if (title.includes(brand)) {
            return brand;
        }
    }
    return null;
}

function buildSearchQuery(product) {
    // Use full title for most accurate platform search results
    return product.title;
}

// Platform links generator — uses brand+category for precise search, sorted by sales
function generatePlatformLink(product) {
    const q = encodeURIComponent(buildSearchQuery(product));
    const platformUrls = {
        taobao: `https://s.taobao.com/search?q=${q}&sort=sale-desc`,
        jd: `https://search.jd.com/Search?keyword=${q}&sort=sort_totalsales15_desc&psort=3`,
        pdd: `https://mobile.yangkeduo.com/search_result.html?search_key=${q}`
    };
    return platformUrls[product.platform] || '#';
}

// Node.js compatibility export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MOCK_PRODUCTS, PLATFORM_NAMES, KNOWN_BRANDS, extractBrand, buildSearchQuery, generatePlatformLink };
}
